dist: jammy
language: python
python:
  - 3.11
jobs:
  include:
    - stage: test
      name: pytest
      install:
        - pip install --upgrade pytest
        - pip install -e .
      script: pytest
    - stage: test
      name: pre-commit
      before_install:
        - git remote set-branches --add origin master
        - git fetch origin master
      install: pip install pre-commit
      script: pre-commit run --show-diff-on-failure --from-ref `git merge-base origin/master ${TRAVIS_COMMIT}` --to-ref ${TRAVIS_COMMIT}

