dist: jammy
language: python
python:
  - 3.11
jobs:
  include:
    - stage: test
      name: pytest
      install:
        - pip install --upgrade pytest
        - pip install -e .
      script: pytest
    - stage: test
      name: pre-commit
      install: pip install pre-commit
      script: >-
        git fetch origin master &&
        echo $TRAVIS_COMMIT &&
        git merge-base origin/master ${TRAVIS_COMMIT} &&
        pre-commit run --show-diff-on-failure --from-ref `git merge-base origin/master ${TRAVIS_COMMIT}` --to-ref ${TRAVIS_COMMIT}

