dist: jammy
language: python
python:
  - 3.14
jobs:
  include:
    - stage: test
      name: pytest
      install:
        - pip install -e .
      script: pytest
    - stage: test
      name: pre-commit
      install: pip install pre-commit
      script: pre-commit run --show-diff-on-failure --all-files

